# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(name='EventData',
                               fields=[
                                   ('id', models.AutoField(auto_created=True,
                                                           primary_key=True,
                                                           serialize=False,
                                                           verbose_name='ID')),
                                   ('username', models.CharField(
                                       blank=True, max_length=255)),
                                   ('title', models.CharField(max_length=255)),
                                   ('description', models.CharField(
                                       blank=True, max_length=255)),
                                   ('location', models.CharField(
                                       blank=True, max_length=255)),
                                   ('startdate', models.DateField()),
                                   ('enddate', models.DateField()),
                                   ('allday', models.BooleanField()),
                                   ('starttime', models.TimeField()),
                                   ('endtime', models.TimeField()),
                                   ('private', models.BooleanField()),
                               ], ),
    ]
