# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
