# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160622_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='allday',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='private',
            field=models.CharField(default=b'false', max_length=5),
        ),
    ]
