# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160625_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdata',
            name='id',
        ),
        migrations.AddField(
            model_name='eventdata',
            name='ukey',
            field=models.CharField(default=b'nnsyj7', max_length=6, primary_key=True, serialize=False),
        ),
    ]
